### ISSUE TITLE
debian image for Orangepi-3b does not boot

### ISSUE THREAD

**Issue by LuisBL** [w568w/u-boot-orangepi-3b#1]
Booting Debian 12 does not work on OrangePi 3B

Image  I got from https://drive.google.com/drive/folders/1-mcXPDx1QpE9ZI8oTivmJ1Nd5HfU5nFv
```

luis@spinoza ~/Téléchargements/Orange3B $ sha
sha1sum       sha224sum     sha256sum     sha384sum     sha512sum     shadowconfig  shasum        
luis@spinoza ~/Téléchargements/Orange3B $ sha256sum Orangepi3b_1.0.6_debian_bookworm_server_linux5.10.160.img
526586d312f1b2bdd8942947b32af8cf99e41294d77345ba03bc8ef177df6730  Orangepi3b_1.0.6_debian_bookworm_server_linux5.10.160.img
luis@spinoza ~/Téléchargements/Orange3B $ cat Orangepi3b_1.0.6_debian_bookworm_server_linux5.10.160.img.sha
526586d312f1b2bdd8942947b32af8cf99e41294d77345ba03bc8ef177df6730 *Orangepi3b_1.0.6_debian_bookworm_server_linux5.10.160.img
luis@spinoza ~/Téléchargements/Orange3B $ 

```

what I see from the USB-to-TTL on ttyACM0 

```
$ screen /dev/ttyACM0 1500000
....
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-rockchip
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default
*** ERROR: `serverip' not set
Config file not found
failed to find reset-gpios property
BOOTP broadcast 1
BOOTP broadcast 2
BOOTP broadcast 3
BOOTP broadcast 4
BOOTP broadcast 5
BOOTP broadcast 6
BOOTP broadcast 7
BOOTP broadcast 8
BOOTP broadcast 9
BOOTP broadcast 10
BOOTP broadcast 11
BOOTP broadcast 12
BOOTP broadcast 13
BOOTP broadcast 14
BOOTP broadcast 15
BOOTP broadcast 16
BOOTP broadcast 17

Retry time exceeded; starting again
Could not get mtd 0
## Booting FIT Image FIT: No fit blob
FIT: No FIT image
Could not find misc partition
Could not find uboot part
=> 

```

**Comment by LuisBL** [comment]
HDMI only show the splash screen git the Orange pi logo

**Comment by w568w** [comment]
In fact I haven't tried a new compiled version in half a year. There may have been some upstream changes that broke previously added patches. 

As soon as I have some time (which could be a couple of weeks later), I'll try to figure out the issue.

Until then, please confirm:

1. Does the version around 81ae41fb7a93d9b1497c4e3b9060fd95bf0f338f work? You can switch to that by executing `git checkout 81ae41fb` and build again;
2. Can you boot with the following commands in U-Boot (you must change MMC partition ID, paths and kernel arguments according to your own settings!):

```
load mmc 0 ${kernel_addr_r} /vmlinuz
load mmc 0 ${fdt_addr_r} /dtbs/rk.dtb
setenv bootargs initrd=/initramfs-linux.img console=ttyS2,1500000 root=PARTUUID=2f3fd9c7-cb58-43ae-978e-60f136cfd91c rw rootwait loglevel=2
booti ${kernel_addr_r} - ${fdt_addr_r}
```
3. And if you really have got some spare time, you can try the most reliable way of debugging: git bisect. 4e1e352395cbbc02d844a3e8a536725ca63396b6 is definitely a good version. Bisect between that and the latest commit. You can figure out the "bad" commit in about 11 trials.

**Comment by w568w** [comment]
And please refer to my discontinued announcement in README. I am not going to maintain this repo since the upstream has supported Orange Pi 3B. Check that ;)

I will close this issue. If you have got any other question, feel free to ask.
